env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

name: Weather Logger

on:
  schedule:
    - cron: '15 13 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python main.py

      # ⭐ここが追加ポイント
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add weather_history.txt
          git commit -m "update weather log" || exit 0
          git push
